// 전문가 레벨 Part 1 - 1000개 단어 (대학/전문가 수준)
const vocabExpert1 = [
    // 학술/연구 심화 (1-100)
    { en: "abate", ko: "줄이다" },
    { en: "aberration", ko: "일탈" },
    { en: "abhor", ko: "혐오하다" },
    { en: "abide", ko: "준수하다" },
    { en: "abjure", ko: "포기하다" },
    { en: "ablaze", ko: "불타는" },
    { en: "abnormality", ko: "이상" },
    { en: "abode", ko: "거처" },
    { en: "aboriginal", ko: "원주민의" },
    { en: "abound", ko: "풍부하다" },
    { en: "abrasive", ko: "마멸성의" },
    { en: "abridge", ko: "요약하다" },
    { en: "abrogate", ko: "폐지하다" },
    { en: "abrupt", ko: "갑작스러운" },
    { en: "abscess", ko: "종기" },
    { en: "abscond", ko: "도주하다" },
    { en: "absolve", ko: "면제하다" },
    { en: "abstain", ko: "삼가다" },
    { en: "abstinence", ko: "금욕" },
    { en: "abstraction", ko: "추상화" },
    { en: "abstruse", ko: "난해한" },
    { en: "absurdity", ko: "불합리" },
    { en: "abyss", ko: "심연" },
    { en: "accede", ko: "동의하다" },
    { en: "accentuate", ko: "강조하다" },
    { en: "acclaim", ko: "칭찬" },
    { en: "accolade", ko: "찬사" },
    { en: "accomplice", ko: "공범" },
    { en: "accredit", ko: "인가하다" },
    { en: "accrue", ko: "발생하다" },
    { en: "acerbic", ko: "신랄한" },
    { en: "acquiesce", ko: "묵인하다" },
    { en: "acquittal", ko: "무죄 선고" },
    { en: "acrid", ko: "매운" },
    { en: "acrimonious", ko: "신랄한" },
    { en: "acrimony", ko: "격렬함" },
    { en: "actuarial", ko: "보험 계리의" },
    { en: "actuate", ko: "작동시키다" },
    { en: "acuity", ko: "예리함" },
    { en: "acumen", ko: "통찰력" },
    { en: "adamant", ko: "단호한" },
    { en: "addendum", ko: "부록" },
    { en: "adherence", ko: "고수" },
    { en: "adherent", ko: "지지자" },
    { en: "adhesive", ko: "접착제" },
    { en: "adjudicate", ko: "판결하다" },
    { en: "adjunct", ko: "부속물" },
    { en: "admonish", ko: "훈계하다" },
    { en: "admonition", ko: "훈계" },
    { en: "adroit", ko: "능숙한" },
    { en: "adulation", ko: "아첨" },
    { en: "adulterate", ko: "불순물을 섞다" },
    { en: "adversary", ko: "적대자" },
    { en: "adversity", ko: "역경" },
    { en: "aegis", ko: "보호" },
    { en: "affable", ko: "상냥한" },
    { en: "affectation", ko: "가식" },
    { en: "affidavit", ko: "진술서" },
    { en: "affiliation", ko: "가입" },
    { en: "affinity", ko: "친밀감" },
    { en: "affluence", ko: "풍요" },
    { en: "affluent", ko: "부유한" },
    { en: "affront", ko: "모욕" },
    { en: "aggrandize", ko: "확대하다" },
    { en: "aggravate", ko: "악화시키다" },
    { en: "aggregate", ko: "집합체" },
    { en: "aghast", ko: "깜짝 놀란" },
    { en: "agile", ko: "민첩한" },
    { en: "agility", ko: "민첩성" },
    { en: "agitate", ko: "선동하다" },
    { en: "agitation", ko: "동요" },
    { en: "agnostic", ko: "불가지론자" },
    { en: "agrarian", ko: "농업의" },
    { en: "alchemy", ko: "연금술" },
    { en: "alcove", ko: "벽감" },
    { en: "algorithm", ko: "알고리즘" },
    { en: "alias", ko: "가명" },
    { en: "alienate", ko: "소외시키다" },
    { en: "alienation", ko: "소외" },
    { en: "allay", ko: "진정시키다" },
    { en: "allegation", ko: "주장" },
    { en: "allege", ko: "주장하다" },
    { en: "allegiance", ko: "충성" },
    { en: "allegorical", ko: "우화적인" },
    { en: "allegory", ko: "우화" },
    { en: "alleviate", ko: "완화하다" },
    { en: "alliteration", ko: "두운법" },
    { en: "allude", ko: "암시하다" },
    { en: "allure", ko: "매혹하다" },
    { en: "allusion", ko: "암시" },
    { en: "altercation", ko: "언쟁" },
    { en: "altruism", ko: "이타주의" },
    { en: "altruistic", ko: "이타적인" },
    { en: "amalgamate", ko: "합병하다" },
    { en: "amalgamation", ko: "합병" },
    { en: "amass", ko: "축적하다" },
    { en: "ambiguity", ko: "모호함" },
    { en: "ambivalence", ko: "양면 감정" },
    { en: "ambivalent", ko: "양면적인" },
    { en: "amble", ko: "한가롭게 걷다" },

    // 법률/정치 심화 (101-200)
    { en: "ameliorate", ko: "개선하다" },
    { en: "amenable", ko: "순응하는" },
    { en: "amenity", ko: "편의시설" },
    { en: "amiable", ko: "친절한" },
    { en: "amicable", ko: "우호적인" },
    { en: "amnesty", ko: "사면" },
    { en: "amorphous", ko: "무정형의" },
    { en: "amortize", ko: "상각하다" },
    { en: "amphibian", ko: "양서류" },
    { en: "amphitheater", ko: "원형극장" },
    { en: "anachronism", ko: "시대착오" },
    { en: "anachronistic", ko: "시대착오적인" },
    { en: "analogous", ko: "유사한" },
    { en: "analogy", ko: "유추" },
    { en: "anarchist", ko: "무정부주의자" },
    { en: "anarchy", ko: "무정부 상태" },
    { en: "anathema", ko: "저주" },
    { en: "anatomical", ko: "해부학적인" },
    { en: "anatomy", ko: "해부학" },
    { en: "ancillary", ko: "부수적인" },
    { en: "anecdote", ko: "일화" },
    { en: "anguish", ko: "고뇌" },
    { en: "animosity", ko: "적의" },
    { en: "annals", ko: "연대기" },
    { en: "annex", ko: "합병하다" },
    { en: "annexation", ko: "합병" },
    { en: "annihilate", ko: "전멸시키다" },
    { en: "annotate", ko: "주석을 달다" },
    { en: "annotation", ko: "주석" },
    { en: "annuity", ko: "연금" },
    { en: "annul", ko: "무효화하다" },
    { en: "anomaly", ko: "변칙" },
    { en: "anonymity", ko: "익명" },
    { en: "antagonism", ko: "적대감" },
    { en: "antagonist", ko: "적대자" },
    { en: "antagonize", ko: "적대시하다" },
    { en: "antecedent", ko: "선행하는" },
    { en: "anthem", ko: "찬가" },
    { en: "anthology", ko: "선집" },
    { en: "anthropology", ko: "인류학" },
    { en: "antibiotic", ko: "항생제" },
    { en: "antibody", ko: "항체" },
    { en: "antidote", ko: "해독제" },
    { en: "antipathy", ko: "반감" },
    { en: "antiquated", ko: "구식의" },
    { en: "antiquity", ko: "고대" },
    { en: "antiseptic", ko: "소독제" },
    { en: "antithesis", ko: "대조" },
    { en: "apathetic", ko: "무관심한" },
    { en: "apathy", ko: "무관심" },
    { en: "apex", ko: "정점" },
    { en: "apocalypse", ko: "종말" },
    { en: "apocalyptic", ko: "종말론적인" },
    { en: "apocryphal", ko: "출처 불명의" },
    { en: "apologetic", ko: "사과하는" },
    { en: "apostle", ko: "사도" },
    { en: "appalling", ko: "끔찍한" },
    { en: "appease", ko: "달래다" },
    { en: "appeasement", ko: "유화" },
    { en: "appellate", ko: "항소의" },
    { en: "append", ko: "첨부하다" },
    { en: "appendix", ko: "부록" },
    { en: "apportion", ko: "배분하다" },
    { en: "apposite", ko: "적절한" },
    { en: "appraisal", ko: "평가" },
    { en: "appraise", ko: "평가하다" },
    { en: "apprehend", ko: "체포하다" },
    { en: "apprehension", ko: "우려" },
    { en: "apprehensive", ko: "염려하는" },
    { en: "apprenticeship", ko: "도제 기간" },
    { en: "approbation", ko: "승인" },
    { en: "apt", ko: "적절한" },
    { en: "aptitude", ko: "적성" },
    { en: "arable", ko: "경작 가능한" },
    { en: "arbiter", ko: "중재자" },
    { en: "arbitrage", ko: "차익 거래" },
    { en: "arbitrary", ko: "임의적인" },
    { en: "arbitrate", ko: "중재하다" },
    { en: "arbitration", ko: "중재" },
    { en: "arcane", ko: "비밀의" },
    { en: "archaic", ko: "고어의" },
    { en: "archetype", ko: "원형" },
    { en: "archipelago", ko: "군도" },
    { en: "ardent", ko: "열렬한" },
    { en: "ardor", ko: "열정" },
    { en: "arduous", ko: "힘든" },
    { en: "aristocracy", ko: "귀족 정치" },
    { en: "aristocrat", ko: "귀족" },
    { en: "arithmetic", ko: "산술" },
    { en: "armament", ko: "군비" },
    { en: "armistice", ko: "휴전" },
    { en: "aromatherapy", ko: "아로마테라피" },
    { en: "arraign", ko: "기소하다" },
    { en: "arrears", ko: "체납금" },
    { en: "arrogance", ko: "오만" },
    { en: "arrogant", ko: "오만한" },
    { en: "arsenal", ko: "무기고" },
    { en: "arson", ko: "방화" },
    { en: "arterial", ko: "동맥의" },
    { en: "artesian", ko: "자분정의" },

    // 의학/과학 심화 (201-300)
    { en: "arthritis", ko: "관절염" },
    { en: "artifice", ko: "책략" },
    { en: "artillery", ko: "포병" },
    { en: "artisan", ko: "장인" },
    { en: "ascendancy", ko: "우세" },
    { en: "ascent", ko: "상승" },
    { en: "ascertain", ko: "확인하다" },
    { en: "ascetic", ko: "금욕주의자" },
    { en: "asceticism", ko: "금욕주의" },
    { en: "ascribe", ko: "귀속시키다" },
    { en: "aseptic", ko: "무균의" },
    { en: "asinine", ko: "어리석은" },
    { en: "askew", ko: "비뚤어진" },
    { en: "aspersion", ko: "중상" },
    { en: "asphyxiate", ko: "질식시키다" },
    { en: "aspirant", ko: "지망자" },
    { en: "assailant", ko: "가해자" },
    { en: "assassinate", ko: "암살하다" },
    { en: "assassination", ko: "암살" },
    { en: "assent", ko: "동의" },
    { en: "assertive", ko: "단호한" },
    { en: "assiduous", ko: "근면한" },
    { en: "assimilate", ko: "동화시키다" },
    { en: "assimilation", ko: "동화" },
    { en: "assuage", ko: "완화하다" },
    { en: "asteroid", ko: "소행성" },
    { en: "asthma", ko: "천식" },
    { en: "asthmatic", ko: "천식의" },
    { en: "astound", ko: "경악시키다" },
    { en: "astray", ko: "방황하여" },
    { en: "astringent", ko: "수렴성의" },
    { en: "astrology", ko: "점성술" },
    { en: "astronomical", ko: "천문학적인" },
    { en: "astute", ko: "기민한" },
    { en: "asylum", ko: "망명" },
    { en: "asymmetric", ko: "비대칭의" },
    { en: "atheism", ko: "무신론" },
    { en: "atheist", ko: "무신론자" },
    { en: "atone", ko: "속죄하다" },
    { en: "atonement", ko: "속죄" },
    { en: "atrocious", ko: "잔학한" },
    { en: "atrocity", ko: "잔학 행위" },
    { en: "atrophy", ko: "위축" },
    { en: "attainment", ko: "성취" },
    { en: "attenuate", ko: "약화시키다" },
    { en: "attest", ko: "증명하다" },
    { en: "attestation", ko: "증명" },
    { en: "attic", ko: "다락방" },
    { en: "attire", ko: "복장" },
    { en: "audacious", ko: "대담한" },
    { en: "audacity", ko: "대담함" },
    { en: "audible", ko: "들을 수 있는" },
    { en: "audition", ko: "오디션" },
    { en: "auditor", ko: "감사관" },
    { en: "auditorium", ko: "강당" },
    { en: "augment", ko: "증가시키다" },
    { en: "augmentation", ko: "증가" },
    { en: "aura", ko: "분위기" },
    { en: "aural", ko: "청각의" },
    { en: "auspices", ko: "후원" },
    { en: "auspicious", ko: "상서로운" },
    { en: "austere", ko: "엄격한" },
    { en: "austerity", ko: "긴축" },
    { en: "authoritarian", ko: "권위주의적인" },
    { en: "authoritarianism", ko: "권위주의" },
    { en: "authoritative", ko: "권위 있는" },
    { en: "autism", ko: "자폐증" },
    { en: "autistic", ko: "자폐증의" },
    { en: "autobiographical", ko: "자서전의" },
    { en: "autobiography", ko: "자서전" },
    { en: "autocracy", ko: "독재 정치" },
    { en: "autocrat", ko: "독재자" },
    { en: "autocratic", ko: "독재적인" },
    { en: "automate", ko: "자동화하다" },
    { en: "automation", ko: "자동화" },
    { en: "autopsy", ko: "부검" },
    { en: "auxiliary", ko: "보조의" },
    { en: "avalanche", ko: "눈사태" },
    { en: "avant-garde", ko: "전위적인" },
    { en: "avarice", ko: "탐욕" },
    { en: "avaricious", ko: "탐욕스러운" },
    { en: "avenge", ko: "복수하다" },
    { en: "averse", ko: "싫어하는" },
    { en: "aversion", ko: "혐오" },
    { en: "avert", ko: "피하다" },
    { en: "aviary", ko: "새장" },
    { en: "avid", ko: "열렬한" },
    { en: "avocation", ko: "부업" },
    { en: "avow", ko: "공언하다" },
    { en: "avowal", ko: "공언" },
    { en: "awry", ko: "비뚤어진" },
    { en: "axiom", ko: "공리" },
    { en: "axiomatic", ko: "자명한" },
    { en: "azure", ko: "하늘색의" },
    { en: "babble", ko: "재잘거리다" },
    { en: "backlash", ko: "반발" },
    { en: "baffle", ko: "당혹시키다" },
    { en: "bait", ko: "미끼" },
    { en: "ballad", ko: "발라드" },
    { en: "ballistic", ko: "탄도의" },

    // 경제/비즈니스 심화 (301-400)
    { en: "banal", ko: "진부한" },
    { en: "banality", ko: "평범함" },
    { en: "bandwagon", ko: "유행" },
    { en: "bane", ko: "골칫거리" },
    { en: "banish", ko: "추방하다" },
    { en: "banishment", ko: "추방" },
    { en: "baptism", ko: "세례" },
    { en: "barb", ko: "미늘" },
    { en: "barbaric", ko: "야만적인" },
    { en: "barbarity", ko: "야만" },
    { en: "barometer", ko: "기압계" },
    { en: "baroque", ko: "바로크의" },
    { en: "barracks", ko: "막사" },
    { en: "barrage", ko: "집중 포화" },
    { en: "barren", ko: "불모의" },
    { en: "barricade", ko: "바리케이드" },
    { en: "bastion", ko: "보루" },
    { en: "bawdy", ko: "음란한" },
    { en: "beacon", ko: "등대" },
    { en: "beatify", ko: "시복하다" },
    { en: "beckon", ko: "손짓하다" },
    { en: "bedlam", ko: "소란" },
    { en: "befuddle", ko: "혼란시키다" },
    { en: "beguile", ko: "속이다" },
    { en: "behemoth", ko: "거대한 것" },
    { en: "behold", ko: "보다" },
    { en: "beholder", ko: "보는 사람" },
    { en: "belated", ko: "뒤늦은" },
    { en: "beleaguer", ko: "포위하다" },
    { en: "belie", ko: "잘못 전하다" },
    { en: "belittle", ko: "경시하다" },
    { en: "bellicose", ko: "호전적인" },
    { en: "belligerent", ko: "교전적인" },
    { en: "bemoan", ko: "한탄하다" },
    { en: "bemused", ko: "어리둥절한" },
    { en: "benediction", ko: "축복" },
    { en: "benefactor", ko: "후원자" },
    { en: "beneficent", ko: "자비로운" },
    { en: "benevolence", ko: "자선" },
    { en: "benevolent", ko: "자비로운" },
    { en: "benign", ko: "온화한" },
    { en: "bequeath", ko: "유증하다" },
    { en: "bequest", ko: "유산" },
    { en: "berate", ko: "꾸짖다" },
    { en: "bereave", ko: "빼앗다" },
    { en: "bereavement", ko: "사별" },
    { en: "bereft", ko: "빼앗긴" },
    { en: "berserk", ko: "광포한" },
    { en: "beseech", ko: "간청하다" },
    { en: "beset", ko: "에워싸다" },
    { en: "besiege", ko: "포위하다" },
    { en: "besmirch", ko: "더럽히다" },
    { en: "bestow", ko: "수여하다" },
    { en: "betrothal", ko: "약혼" },
    { en: "bewilder", ko: "당황하게 하다" },
    { en: "bewilderment", ko: "당혹" },
    { en: "bicameral", ko: "양원제의" },
    { en: "bicker", ko: "언쟁하다" },
    { en: "bigot", ko: "편협한 사람" },
    { en: "bigotry", ko: "편협" },
    { en: "bilateral", ko: "양자간의" },
    { en: "biodegradable", ko: "생분해성의" },
    { en: "biodiversity", ko: "생물 다양성" },
    { en: "biofuel", ko: "바이오 연료" },
    { en: "biomass", ko: "바이오매스" },
    { en: "biometric", ko: "생체 인식의" },
    { en: "biosphere", ko: "생물권" },
    { en: "biotechnology", ko: "생명 공학" },
    { en: "bipartisan", ko: "초당파적인" },
    { en: "bisect", ko: "이등분하다" },
    { en: "bivouac", ko: "야영하다" },
    { en: "blackmail", ko: "협박" },
    { en: "blandish", ko: "아첨하다" },
    { en: "blandishment", ko: "아첨" },
    { en: "blaspheme", ko: "신성 모독하다" },
    { en: "blasphemous", ko: "신성 모독적인" },
    { en: "blasphemy", ko: "신성 모독" },
    { en: "blatant", ko: "노골적인" },
    { en: "bleach", ko: "표백하다" },
    { en: "bleak", ko: "황량한" },
    { en: "blemish", ko: "결점" },
    { en: "blight", ko: "황폐시키다" },
    { en: "bliss", ko: "더없는 행복" },
    { en: "blissful", ko: "더없이 행복한" },
    { en: "blithe", ko: "태평한" },
    { en: "bloat", ko: "부풀리다" },
    { en: "blockade", ko: "봉쇄" },
    { en: "bloodshed", ko: "유혈" },
    { en: "blunder", ko: "실수" },
    { en: "blunt", ko: "무딘" },
    { en: "boast", ko: "자랑하다" },
    { en: "bodily", ko: "육체의" },
    { en: "bog", ko: "수렁" },
    { en: "boggle", ko: "놀라다" },
    { en: "bogus", ko: "가짜의" },
    { en: "bohemian", ko: "보헤미안의" },
    { en: "boisterous", ko: "떠들썩한" },
    { en: "bolster", ko: "지지하다" },
    { en: "bombard", ko: "폭격하다" },
    { en: "bombardment", ko: "폭격" },

    // 철학/심리 심화 (401-500)
    { en: "bombastic", ko: "과장된" },
    { en: "bona fide", ko: "진정한" },
    { en: "bondage", ko: "속박" },
    { en: "bonfire", ko: "모닥불" },
    { en: "boon", ko: "은혜" },
    { en: "boorish", ko: "무례한" },
    { en: "bootleg", ko: "밀수품" },
    { en: "booty", ko: "전리품" },
    { en: "botch", ko: "망치다" },
    { en: "bounty", ko: "현상금" },
    { en: "bourgeois", ko: "부르주아의" },
    { en: "bourgeoisie", ko: "부르주아지" },
    { en: "bout", ko: "한판" },
    { en: "boycott", ko: "보이콧" },
    { en: "brace", ko: "버팀대" },
    { en: "brackish", ko: "약간 짠" },
    { en: "brag", ko: "자랑하다" },
    { en: "brandish", ko: "휘두르다" },
    { en: "brash", ko: "성급한" },
    { en: "bravado", ko: "허세" },
    { en: "brawl", ko: "싸움" },
    { en: "brazen", ko: "뻔뻔스러운" },
    { en: "breadth", ko: "폭" },
    { en: "brevity", ko: "간결" },
    { en: "brink", ko: "가장자리" },
    { en: "bristle", ko: "강모" },
    { en: "broach", ko: "꺼내다" },
    { en: "brocade", ko: "비단" },
    { en: "brood", ko: "곰곰이 생각하다" },
    { en: "browbeat", ko: "위협하다" },
    { en: "brusque", ko: "퉁명스러운" },
    { en: "bucolic", ko: "전원의" },
    { en: "buffer", ko: "완충장치" },
    { en: "buffet", ko: "강타하다" },
    { en: "buffoon", ko: "어릿광대" },
    { en: "bulbous", ko: "구근의" },
    { en: "bullion", ko: "금괴" },
    { en: "bully", ko: "약자를 괴롭히다" },
    { en: "bulwark", ko: "방벽" },
    { en: "bumble", ko: "어설프게 하다" },
    { en: "buoyancy", ko: "부력" },
    { en: "buoyant", ko: "부유하는" },
    { en: "bureaucrat", ko: "관료" },
    { en: "bureaucratic", ko: "관료적인" },
    { en: "burgeon", ko: "급성장하다" },
    { en: "burglar", ko: "강도" },
    { en: "burglary", ko: "강도질" },
    { en: "burlesque", ko: "희화화" },
    { en: "burnish", ko: "닦다" },
    { en: "buttress", ko: "지지하다" },
    { en: "bylaw", ko: "조례" },
    { en: "bypass", ko: "우회하다" },
    { en: "byproduct", ko: "부산물" },
    { en: "byzantine", ko: "복잡한" },
    { en: "cabal", ko: "음모단" },
    { en: "cache", ko: "은닉처" },
    { en: "cacophonous", ko: "불협화음의" },
    { en: "cacophony", ko: "불협화음" },
    { en: "cadaver", ko: "시체" },
    { en: "cadence", ko: "운율" },
    { en: "cadet", ko: "사관 생도" },
    { en: "cajole", ko: "감언이설로 꾀다" },
    { en: "calamity", ko: "재앙" },
    { en: "caliber", ko: "구경" },
    { en: "calibrate", ko: "보정하다" },
    { en: "calibration", ko: "보정" },
    { en: "callous", ko: "냉담한" },
    { en: "callow", ko: "미숙한" },
    { en: "calumny", ko: "중상" },
    { en: "camaraderie", ko: "동지애" },
    { en: "camouflage", ko: "위장" },
    { en: "canard", ko: "허위 보도" },
    { en: "candid", ko: "솔직한" },
    { en: "candor", ko: "솔직함" },
    { en: "canine", ko: "개의" },
    { en: "canny", ko: "영리한" },
    { en: "canon", ko: "규범" },
    { en: "canonical", ko: "정전의" },
    { en: "canopy", ko: "캐노피" },
    { en: "cantankerous", ko: "성미가 까다로운" },
    { en: "canvass", ko: "유세하다" },
    { en: "capacious", ko: "넓은" },
    { en: "capillary", ko: "모세관" },
    { en: "capitulate", ko: "항복하다" },
    { en: "capitulation", ko: "항복" },
    { en: "capricious", ko: "변덕스러운" },
    { en: "captivate", ko: "매혹하다" },
    { en: "captivity", ko: "포로" },
    { en: "carcass", ko: "사체" },
    { en: "carcinogen", ko: "발암물질" },
    { en: "carcinogenic", ko: "발암성의" },
    { en: "cardiac", ko: "심장의" },
    { en: "cardinal", ko: "기본적인" },
    { en: "cardiovascular", ko: "심혈관의" },
    { en: "careen", ko: "기울다" },
    { en: "caricature", ko: "풍자화" },
    { en: "carnage", ko: "대학살" },
    { en: "carnal", ko: "육체의" },
    { en: "carnivore", ko: "육식동물" },
    { en: "carnivorous", ko: "육식성의" },

    // 환경/에너지 심화 (501-600)
    { en: "carouse", ko: "흥청거리다" },
    { en: "carp", ko: "트집잡다" },
    { en: "carrion", ko: "썩은 고기" },
    { en: "cartography", ko: "지도 제작술" },
    { en: "cascade", ko: "폭포수" },
    { en: "castigate", ko: "엄하게 꾸짖다" },
    { en: "castigation", ko: "엄한 질책" },
    { en: "casualty", ko: "사상자" },
    { en: "cataclysm", ko: "대변동" },
    { en: "cataclysmic", ko: "대격변의" },
    { en: "catalyst", ko: "촉매" },
    { en: "catalyze", ko: "촉진하다" },
    { en: "catapult", ko: "투석기" },
    { en: "cataract", ko: "백내장" },
    { en: "categorical", ko: "무조건적인" },
    { en: "categorize", ko: "분류하다" },
    { en: "cater", ko: "음식을 제공하다" },
    { en: "catharsis", ko: "정화" },
    { en: "cathartic", ko: "정화의" },
    { en: "caucus", ko: "당원 총회" },
    { en: "cauldron", ko: "큰 솥" },
    { en: "causality", ko: "인과관계" },
    { en: "caustic", ko: "부식성의" },
    { en: "cauterize", ko: "소작하다" },
    { en: "cavalier", ko: "거만한" },
    { en: "cavalry", ko: "기병대" },
    { en: "caveat", ko: "경고" },
    { en: "cavern", ko: "큰 동굴" },
    { en: "cavernous", ko: "동굴 같은" },
    { en: "cavort", ko: "까불다" },
    { en: "cede", ko: "양도하다" },
    { en: "celestial", ko: "천상의" },
    { en: "celibacy", ko: "독신" },
    { en: "celibate", ko: "독신의" },
    { en: "cellular", ko: "세포의" },
    { en: "censor", ko: "검열하다" },
    { en: "censorship", ko: "검열" },
    { en: "censure", ko: "비난" },
    { en: "centenary", ko: "100주년" },
    { en: "centennial", ko: "100년의" },
    { en: "centigrade", ko: "섭씨의" },
    { en: "centrifugal", ko: "원심력의" },
    { en: "centurion", ko: "백부장" },
    { en: "cerebral", ko: "대뇌의" },
    { en: "ceremonial", ko: "의식의" },
    { en: "certitude", ko: "확신" },
    { en: "cessation", ko: "중단" },
    { en: "chafe", ko: "쓸리다" },
    { en: "chaff", ko: "겨" },
    { en: "chagrin", ko: "분함" },
    { en: "chameleon", ko: "카멜레온" },
    { en: "chancellor", ko: "수상" },
    { en: "chandelier", ko: "샹들리에" },
    { en: "changeling", ko: "바꿔치기 아이" },
    { en: "chant", ko: "성가" },
    { en: "chaotic", ko: "혼란스러운" },
    { en: "chaperone", ko: "보호자" },
    { en: "chaplain", ko: "목사" },
    { en: "char", ko: "숯이 되다" },
    { en: "charade", ko: "제스처 게임" },
    { en: "charisma", ko: "카리스마" },
    { en: "charismatic", ko: "카리스마 있는" },
    { en: "charitable", ko: "자선적인" },
    { en: "charlatan", ko: "사기꾼" },
    { en: "chaste", ko: "순결한" },
    { en: "chastise", ko: "엄하게 꾸짖다" },
    { en: "chastity", ko: "순결" },
    { en: "chattel", ko: "동산" },
    { en: "chauvinism", ko: "맹목적 애국심" },
    { en: "chauvinist", ko: "맹목적 애국자" },
    { en: "checkered", ko: "파란만장한" },
    { en: "cherubic", ko: "천사 같은" },
    { en: "chide", ko: "꾸짖다" },
    { en: "chimera", ko: "키메라" },
    { en: "chimerical", ko: "몽상적인" },
    { en: "chisel", ko: "끌" },
    { en: "chivalrous", ko: "기사도적인" },
    { en: "chivalry", ko: "기사도" },
    { en: "cholesterol", ko: "콜레스테롤" },
    { en: "choreograph", ko: "안무하다" },
    { en: "choreographer", ko: "안무가" },
    { en: "choreography", ko: "안무" },
    { en: "chromatic", ko: "색채의" },
    { en: "chromosome", ko: "염색체" },
    { en: "chronic", ko: "만성적인" },
    { en: "chronically", ko: "만성적으로" },
    { en: "chronicle", ko: "연대기" },
    { en: "chronological", ko: "연대순의" },
    { en: "chronology", ko: "연대기" },
    { en: "churlish", ko: "무례한" },
    { en: "cipher", ko: "암호" },
    { en: "circuitous", ko: "우회하는" },
    { en: "circumference", ko: "원주" },
    { en: "circumlocution", ko: "우회적 표현" },
    { en: "circumscribe", ko: "제한하다" },
    { en: "circumspect", ko: "신중한" },
    { en: "circumvent", ko: "회피하다" },
    { en: "citadel", ko: "성채" },
    { en: "citation", ko: "인용" },
    { en: "civility", ko: "예의" },
    { en: "clairvoyant", ko: "투시력이 있는" },

    // 예술/문학 심화 (601-700)
    { en: "clamber", ko: "기어오르다" },
    { en: "clamor", ko: "소란" },
    { en: "clamorous", ko: "시끄러운" },
    { en: "clandestine", ko: "은밀한" },
    { en: "clang", ko: "쨍그랑 울리다" },
    { en: "clangor", ko: "쨍그랑거리는 소리" },
    { en: "claptrap", ko: "허튼 소리" },
    { en: "clarion", ko: "명료한" },
    { en: "clasp", ko: "꽉 쥐다" },
    { en: "clatter", ko: "덜컹거리다" },
    { en: "claustrophobia", ko: "폐소공포증" },
    { en: "cleanse", ko: "정화하다" },
    { en: "clemency", ko: "관용" },
    { en: "clement", ko: "온화한" },
    { en: "clergy", ko: "성직자" },
    { en: "clerical", ko: "사무의" },
    { en: "clientele", ko: "고객층" },
    { en: "climactic", ko: "절정의" },
    { en: "cling", ko: "달라붙다" },
    { en: "clique", ko: "파벌" },
    { en: "cloister", ko: "수도원" },
    { en: "clone", ko: "복제하다" },
    { en: "clot", ko: "응고하다" },
    { en: "clout", ko: "영향력" },
    { en: "cloying", ko: "지나치게 달콤한" },
    { en: "clumsy", ko: "서투른" },
    { en: "coagulate", ko: "응고하다" },
    { en: "coalesce", ko: "합체하다" },
    { en: "coarse", ko: "거친" },
    { en: "coax", ko: "구슬리다" },
    { en: "cobble", ko: "조약돌" },
    { en: "coddle", ko: "소중히 다루다" },
    { en: "codify", ko: "법전화하다" },
    { en: "coerce", ko: "강제하다" },
    { en: "coercion", ko: "강제" },
    { en: "coercive", ko: "강압적인" },
    { en: "coexist", ko: "공존하다" },
    { en: "coexistence", ko: "공존" },
    { en: "cogent", ko: "설득력 있는" },
    { en: "cogitate", ko: "숙고하다" },
    { en: "cognition", ko: "인지" },
    { en: "cognizance", ko: "인식" },
    { en: "cognizant", ko: "인식하고 있는" },
    { en: "cohabit", ko: "동거하다" },
    { en: "cohabitation", ko: "동거" },
    { en: "cohere", ko: "결합하다" },
    { en: "coherence", ko: "일관성" },
    { en: "cohesion", ko: "결합" },
    { en: "cohesive", ko: "결합력 있는" },
    { en: "cohort", ko: "동료" },
    { en: "coincidental", ko: "우연의" },
    { en: "collaborate", ko: "협력하다" },
    { en: "collaborator", ko: "협력자" },
    { en: "collage", ko: "콜라주" },
    { en: "collateral", ko: "담보물" },
    { en: "collation", ko: "대조" },
    { en: "collide", ko: "충돌하다" },
    { en: "collision", ko: "충돌" },
    { en: "colloquial", ko: "구어의" },
    { en: "colloquialism", ko: "구어체" },
    { en: "collusion", ko: "공모" },
    { en: "colonialism", ko: "식민주의" },
    { en: "colonize", ko: "식민지화하다" },
    { en: "colonnade", ko: "열주" },
    { en: "colossal", ko: "거대한" },
    { en: "colossus", ko: "거인" },
    { en: "coma", ko: "혼수상태" },
    { en: "comatose", ko: "혼수상태의" },
    { en: "combatant", ko: "전투원" },
    { en: "combustible", ko: "가연성의" },
    { en: "combustion", ko: "연소" },
    { en: "comeback", ko: "복귀" },
    { en: "comedian", ko: "코미디언" },
    { en: "comely", ko: "아름다운" },
    { en: "comet", ko: "혜성" },
    { en: "comeuppance", ko: "응보" },
    { en: "comical", ko: "우스운" },
    { en: "commandeer", ko: "징발하다" },
    { en: "commandment", ko: "계명" },
    { en: "commemoration", ko: "기념" },
    { en: "commencement", ko: "개시" },
    { en: "commend", ko: "칭찬하다" },
    { en: "commendable", ko: "칭찬할 만한" },
    { en: "commendation", ko: "칭찬" },
    { en: "commensurate", ko: "상응하는" },
    { en: "commentary", ko: "논평" },
    { en: "commentator", ko: "해설자" },
    { en: "commissar", ko: "인민위원" },
    { en: "commissary", ko: "매점" },
    { en: "commissioner", ko: "위원" },
    { en: "commitment", ko: "헌신" },
    { en: "commodious", ko: "널찍한" },
    { en: "commonplace", ko: "평범한" },
    { en: "commonwealth", ko: "연방" },
    { en: "commotion", ko: "소동" },
    { en: "communal", ko: "공동의" },
    { en: "commune", ko: "공동체" },
    { en: "communicable", ko: "전염성의" },
    { en: "communion", ko: "영성체" },
    { en: "communique", ko: "공식 발표" },
    { en: "commute", ko: "통근하다" },

    // 기술/IT 심화 (701-800)
    { en: "commuter", ko: "통근자" },
    { en: "compact", ko: "조밀한" },
    { en: "companionship", ko: "교우 관계" },
    { en: "comparatively", ko: "비교적" },
    { en: "compartment", ko: "구획" },
    { en: "compassionate", ko: "자비로운" },
    { en: "compatibility", ko: "호환성" },
    { en: "compatriot", ko: "동포" },
    { en: "compelling", ko: "강력한" },
    { en: "compendium", ko: "개요" },
    { en: "compensatory", ko: "보상의" },
    { en: "competency", ko: "능력" },
    { en: "compilation", ko: "편집물" },
    { en: "complacency", ko: "안주" },
    { en: "complacent", ko: "안주하는" },
    { en: "complementary", ko: "보완적인" },
    { en: "complexion", ko: "안색" },
    { en: "compliant", ko: "순응하는" },
    { en: "complicatedion", ko: "합병증" },
    { en: "complicity", ko: "공모" },
    { en: "complimentary", ko: "무료의" },
    { en: "composure", ko: "침착" },
    { en: "comprehensible", ko: "이해할 수 있는" },
    { en: "compression", ko: "압축" },
    { en: "compulsion", ko: "강제" },
    { en: "compulsive", ko: "강박적인" },
    { en: "compunction", ko: "양심의 가책" },
    { en: "computation", ko: "계산" },
    { en: "computational", ko: "계산의" },
    { en: "computerize", ko: "전산화하다" },
    { en: "comrade", ko: "동지" },
    { en: "comradeship", ko: "동지애" },
    { en: "concave", ko: "오목한" },
    { en: "concealment", ko: "은닉" },
    { en: "conceit", ko: "자만" },
    { en: "conceited", ko: "자만하는" },
    { en: "conceivable", ko: "상상할 수 있는" },
    { en: "concentric", ko: "동심원의" },
    { en: "conception", ko: "개념" },
    { en: "conceptual", ko: "개념의" },
    { en: "conceptualize", ko: "개념화하다" },
    { en: "concession", ko: "양보" },
    { en: "concierge", ko: "안내인" },
    { en: "conciliate", ko: "달래다" },
    { en: "conciliation", ko: "화해" },
    { en: "conciliatory", ko: "화해적인" },
    { en: "concise", ko: "간결한" },
    { en: "conclave", ko: "비밀 회의" },
    { en: "conclusive", ko: "결정적인" },
    { en: "concoct", ko: "만들어내다" },
    { en: "concoction", ko: "혼합물" },
    { en: "concomitant", ko: "수반하는" },
    { en: "concord", ko: "화합" },
    { en: "concordance", ko: "일치" },
    { en: "concourse", ko: "집합장소" },
    { en: "concrete", ko: "구체적인" },
    { en: "concubine", ko: "첩" },
    { en: "concur", ko: "동의하다" },
    { en: "concurrence", ko: "동의" },
    { en: "concurrent", ko: "동시의" },
    { en: "concussion", ko: "뇌진탕" },
    { en: "condemnation", ko: "비난" },
    { en: "condensation", ko: "응축" },
    { en: "condescend", ko: "겸손히 하다" },
    { en: "condescending", ko: "거들먹거리는" },
    { en: "condescension", ko: "거들먹거림" },
    { en: "condiment", ko: "조미료" },
    { en: "conditional", ko: "조건적인" },
    { en: "condolence", ko: "애도" },
    { en: "condominium", ko: "콘도" },
    { en: "condone", ko: "묵과하다" },
    { en: "conducive", ko: "도움이 되는" },
    { en: "conduit", ko: "도관" },
    { en: "confederacy", ko: "동맹" },
    { en: "confederate", ko: "동맹국" },
    { en: "conferral", ko: "수여" },
    { en: "confide", ko: "털어놓다" },
    { en: "confidential", ko: "비밀의" },
    { en: "confidentiality", ko: "기밀성" },
    { en: "configuration", ko: "배치" },
    { en: "confinement", ko: "감금" },
    { en: "confiscate", ko: "몰수하다" },
    { en: "confiscation", ko: "몰수" },
    { en: "conflagration", ko: "대화재" },
    { en: "confluence", ko: "합류" },
    { en: "conform", ko: "순응하다" },
    { en: "conformist", ko: "순응주의자" },
    { en: "conformity", ko: "순응" },
    { en: "confound", ko: "혼란시키다" },
    { en: "confront", ko: "직면하다" },
    { en: "confrontational", ko: "대립적인" },
    { en: "congeal", ko: "응고하다" },
    { en: "congenial", ko: "마음이 맞는" },
    { en: "congenital", ko: "선천적인" },
    { en: "congest", ko: "혼잡하게 하다" },
    { en: "congestion", ko: "혼잡" },
    { en: "conglomerate", ko: "대기업" },
    { en: "conglomeration", ko: "집합체" },
    { en: "congregate", ko: "모이다" },
    { en: "congressional", ko: "의회의" },

    // 국제관계/외교 심화 (801-900)
    { en: "congruence", ko: "일치" },
    { en: "congruent", ko: "일치하는" },
    { en: "conical", ko: "원뿔의" },
    { en: "conifer", ko: "침엽수" },
    { en: "coniferous", ko: "침엽수의" },
    { en: "conjecture", ko: "추측" },
    { en: "conjugal", ko: "부부의" },
    { en: "conjugate", ko: "활용하다" },
    { en: "conjure", ko: "마술로 나타내다" },
    { en: "connive", ko: "묵인하다" },
    { en: "connoisseur", ko: "감정가" },
    { en: "connotation", ko: "함축" },
    { en: "connote", ko: "암시하다" },
    { en: "connubial", ko: "결혼의" },
    { en: "conscientious", ko: "양심적인" },
    { en: "conscript", ko: "징집병" },
    { en: "conscription", ko: "징집" },
    { en: "consecrate", ko: "봉헌하다" },
    { en: "consecration", ko: "봉헌" },
    { en: "consensual", ko: "합의에 의한" },
    { en: "consequential", ko: "중대한" },
    { en: "conservatism", ko: "보수주의" },
    { en: "conservatory", ko: "온실" },
    { en: "consign", ko: "맡기다" },
    { en: "consignment", ko: "위탁" },
    { en: "consolation", ko: "위안" },
    { en: "consolidation", ko: "통합" },
    { en: "consonance", ko: "조화" },
    { en: "consonant", ko: "자음" },
    { en: "consort", ko: "배우자" },
    { en: "consortium", ko: "컨소시엄" },
    { en: "conspicuous", ko: "눈에 띄는" },
    { en: "conspirator", ko: "공모자" },
    { en: "conspire", ko: "공모하다" },
    { en: "constancy", ko: "일관성" },
    { en: "constellation", ko: "별자리" },
    { en: "consternation", ko: "경악" },
    { en: "constipation", ko: "변비" },
    { en: "constituent", ko: "구성원" },
    { en: "constitutional", ko: "헌법적인" },
    { en: "constrain", ko: "억제하다" },
    { en: "constrict", ko: "조이다" },
    { en: "constriction", ko: "수축" },
    { en: "constructive", ko: "건설적인" },
    { en: "construe", ko: "해석하다" },
    { en: "consul", ko: "영사" },
    { en: "consular", ko: "영사의" },
    { en: "consulate", ko: "영사관" },
    { en: "consummate", ko: "완벽한" },
    { en: "consummation", ko: "완성" },
    { en: "contagion", ko: "전염" },
    { en: "contagious", ko: "전염성의" },
    { en: "containment", ko: "봉쇄" },
    { en: "contamination", ko: "오염" },
    { en: "contemplation", ko: "숙고" },
    { en: "contemplative", ko: "사색적인" },
    { en: "contemporaneous", ko: "동시대의" },
    { en: "contemptible", ko: "비열한" },
    { en: "contemptuous", ko: "경멸하는" },
    { en: "contender", ko: "경쟁자" },
    { en: "contention", ko: "주장" },
    { en: "contentious", ko: "논쟁적인" },
    { en: "contentment", ko: "만족" },
    { en: "contextualize", ko: "맥락화하다" },
    { en: "contiguous", ko: "인접한" },
    { en: "continence", ko: "자제" },
    { en: "contingency", ko: "우발사태" },
    { en: "contort", ko: "뒤틀다" },
    { en: "contortion", ko: "비틀기" },
    { en: "contraband", ko: "밀수품" },
    { en: "contraception", ko: "피임" },
    { en: "contraceptive", ko: "피임약" },
    { en: "contraction", ko: "수축" },
    { en: "contradict", ko: "부정하다" },
    { en: "contradictory", ko: "모순된" },
    { en: "contraption", ko: "기묘한 장치" },
    { en: "contravene", ko: "위반하다" },
    { en: "contravention", ko: "위반" },
    { en: "contrite", ko: "뉘우치는" },
    { en: "contrition", ko: "회한" },
    { en: "contrivance", ko: "고안물" },
    { en: "contrive", ko: "고안하다" },
    { en: "contrived", ko: "부자연스러운" },
    { en: "controller", ko: "관리자" },
    { en: "controversial", ko: "논쟁적인" },
    { en: "contusion", ko: "타박상" },
    { en: "conundrum", ko: "난제" },
    { en: "convalesce", ko: "회복하다" },
    { en: "convalescence", ko: "회복기" },
    { en: "convene", ko: "소집하다" },
    { en: "convergence", ko: "수렴" },
    { en: "convergent", ko: "수렴하는" },
    { en: "conversant", ko: "정통한" },
    { en: "converse", ko: "반대" },
    { en: "conversely", ko: "반대로" },
    { en: "converter", ko: "변환기" },
    { en: "convertible", ko: "전환 가능한" },
    { en: "convex", ko: "볼록한" },
    { en: "conveyance", ko: "운반" },
    { en: "conveyor", ko: "컨베이어" },

    // 마무리 (901-1000)
    { en: "convivial", ko: "사교적인" },
    { en: "convocation", ko: "집회" },
    { en: "convoluted", ko: "복잡한" },
    { en: "convolution", ko: "복잡함" },
    { en: "convoy", ko: "호송대" },
    { en: "convulse", ko: "경련을 일으키다" },
    { en: "convulsion", ko: "경련" },
    { en: "coolant", ko: "냉각제" },
    { en: "cooperate", ko: "협력하다" },
    { en: "cooperative", ko: "협동의" },
    { en: "coordinate", ko: "조정하다" },
    { en: "coordination", ko: "조정" },
    { en: "coordinator", ko: "조정자" },
    { en: "copious", ko: "다량의" },
    { en: "copyright", ko: "저작권" },
    { en: "cordial", ko: "다정한" },
    { en: "cordiality", ko: "다정함" },
    { en: "cordon", ko: "경비선" },
    { en: "cornerstone", ko: "초석" },
    { en: "corollary", ko: "당연한 결과" },
    { en: "coronary", ko: "관상동맥의" },
    { en: "coronation", ko: "대관식" },
    { en: "coroner", ko: "검시관" },
    { en: "corporal", ko: "신체의" },
    { en: "corporeal", ko: "육체의" },
    { en: "corral", ko: "가축 우리" },
    { en: "corrective", ko: "교정의" },
    { en: "correlate", ko: "상관시키다" },
    { en: "corroborate", ko: "확증하다" },
    { en: "corroboration", ko: "확증" },
    { en: "corrode", ko: "부식시키다" },
    { en: "corrosion", ko: "부식" },
    { en: "corrosive", ko: "부식성의" },
    { en: "corrugate", ko: "주름지게 하다" },
    { en: "cortex", ko: "피질" },
    { en: "cosmetic", ko: "화장품의" },
    { en: "cosmetology", ko: "미용학" },
    { en: "cosmopolitan", ko: "국제적인" },
    { en: "cosmos", ko: "우주" },
    { en: "counteract", ko: "방해하다" },
    { en: "counterbalance", ko: "상쇄하다" },
    { en: "counterfeit", ko: "위조품" },
    { en: "counterintuitive", ko: "직관에 반하는" },
    { en: "countermand", ko: "철회하다" },
    { en: "counterpart", ko: "상대편" },
    { en: "counterproductive", ko: "역효과의" },
    { en: "countersign", ko: "부서하다" },
    { en: "countervail", ko: "대항하다" },
    { en: "coup", ko: "쿠데타" },
    { en: "courageous", ko: "용감한" },
    { en: "courier", ko: "배달원" },
    { en: "courteous", ko: "공손한" },
    { en: "courtyard", ko: "안마당" },
    { en: "covenant", ko: "계약" },
    { en: "covert", ko: "은밀한" },
    { en: "covet", ko: "갈망하다" },
    { en: "covetous", ko: "탐내는" },
    { en: "cowardice", ko: "비겁" },
    { en: "cowardly", ko: "비겁한" },
    { en: "cower", ko: "움츠리다" },
    { en: "crackdown", ko: "단속" },
    { en: "cradle", ko: "요람" },
    { en: "craftsman", ko: "장인" },
    { en: "craftsmanship", ko: "장인정신" },
    { en: "crafty", ko: "교활한" },
    { en: "cram", ko: "벼락치기 하다" },
    { en: "cramp", ko: "경련" },
    { en: "cramped", ko: "비좁은" },
    { en: "cranium", ko: "두개골" },
    { en: "crank", ko: "크랭크" },
    { en: "crass", ko: "천박한" },
    { en: "crater", ko: "분화구" },
    { en: "crave", ko: "갈망하다" },
    { en: "craven", ko: "비겁한" },
    { en: "craving", ko: "갈망" },
    { en: "crawl", ko: "기다" },
    { en: "craze", ko: "열풍" },
    { en: "credence", ko: "신뢰" },
    { en: "credential", ko: "자격증" },
    { en: "credibility", ko: "신뢰성" },
    { en: "creditor", ko: "채권자" },
    { en: "credulity", ko: "속기 쉬움" },
    { en: "credulous", ko: "쉽게 믿는" },
    { en: "creed", ko: "신조" },
    { en: "cremate", ko: "화장하다" },
    { en: "cremation", ko: "화장" },
    { en: "crescendo", ko: "크레센도" },
    { en: "crescent", ko: "초승달 모양의" },
    { en: "crest", ko: "정상" },
    { en: "crestfallen", ko: "풀이 죽은" },
    { en: "crevice", ko: "갈라진 틈" },
    { en: "cringe", ko: "움츠리다" },
    { en: "crinkle", ko: "주름" },
    { en: "cripple", ko: "불구로 만들다" },
    { en: "crisp", ko: "바삭바삭한" },
    { en: "crisscross", ko: "십자형으로 교차하다" },
    { en: "criterion", ko: "기준" },
    { en: "critique", ko: "비평" },
    { en: "croak", ko: "개굴개굴 울다" },
    { en: "crochet", ko: "코바늘뜨기" },
    { en: "crockery", ko: "도기류" }
];
