// 전문가 레벨 Part 2 - 1000개 단어 (대학/전문가 수준)
const vocabExpert2 = [
    // D-E (1-100)
    { en: "crony", ko: "측근" },
    { en: "cronyism", ko: "정실주의" },
    { en: "crossbreed", ko: "교배하다" },
    { en: "crossroads", ko: "교차로" },
    { en: "crouch", ko: "웅크리다" },
    { en: "crucible", ko: "도가니" },
    { en: "crucify", ko: "십자가에 못박다" },
    { en: "crude", ko: "천연의" },
    { en: "cruiser", ko: "순양함" },
    { en: "crumble", ko: "부스러지다" },
    { en: "crunch", ko: "위기" },
    { en: "crusade", ko: "십자군" },
    { en: "crusader", ko: "십자군 전사" },
    { en: "cryptic", ko: "수수께끼 같은" },
    { en: "crystallize", ko: "결정화하다" },
    { en: "cubicle", ko: "칸막이" },
    { en: "cue", ko: "신호" },
    { en: "culminate", ko: "최고조에 달하다" },
    { en: "culmination", ko: "절정" },
    { en: "culpable", ko: "비난받을 만한" },
    { en: "culprit", ko: "범인" },
    { en: "cult", ko: "사이비 종교" },
    { en: "cultivate", ko: "경작하다" },
    { en: "cumbersome", ko: "다루기 힘든" },
    { en: "cumulative", ko: "누적의" },
    { en: "cunning", ko: "교활한" },
    { en: "curator", ko: "큐레이터" },
    { en: "curb", ko: "억제하다" },
    { en: "curfew", ko: "통행금지" },
    { en: "curiosity", ko: "호기심" },
    { en: "curmudgeon", ko: "심술꾸러기" },
    { en: "cursory", ko: "피상적인" },
    { en: "curt", ko: "무뚝뚝한" },
    { en: "curtail", ko: "삭감하다" },
    { en: "cynical", ko: "냉소적인" },
    { en: "cynicism", ko: "냉소주의" },
    { en: "czar", ko: "차르" },
    { en: "dagger", ko: "단검" },
    { en: "dainty", ko: "섬세한" },
    { en: "dais", ko: "연단" },
    { en: "dalliance", ko: "빈둥거림" },
    { en: "dampen", ko: "축축하게 하다" },
    { en: "dangle", ko: "매달리다" },
    { en: "dapper", ko: "말쑥한" },
    { en: "daredevil", ko: "무모한 사람" },
    { en: "dart", ko: "돌진하다" },
    { en: "daunt", ko: "위협하다" },
    { en: "daunting", ko: "주눅들게 하는" },
    { en: "dauntless", ko: "두려움 없는" },
    { en: "dawdle", ko: "빈둥거리다" },
    { en: "daze", ko: "멍하게 하다" },
    { en: "dazzle", ko: "눈부시게 하다" },
    { en: "deacon", ko: "부제" },
    { en: "deactivate", ko: "비활성화하다" },
    { en: "deadlock", ko: "교착상태" },
    { en: "dealership", ko: "대리점" },
    { en: "dean", ko: "학장" },
    { en: "dearth", ko: "부족" },
    { en: "debacle", ko: "대실패" },
    { en: "debase", ko: "품위를 떨어뜨리다" },
    { en: "debatable", ko: "논쟁의 여지가 있는" },
    { en: "debauchery", ko: "방탕" },
    { en: "debilitate", ko: "약화시키다" },
    { en: "debility", ko: "쇠약" },
    { en: "debit", ko: "차변" },
    { en: "debonair", ko: "쾌활한" },
    { en: "debrief", ko: "보고를 받다" },
    { en: "debris", ko: "잔해" },
    { en: "debtor", ko: "채무자" },
    { en: "debunk", ko: "폭로하다" },
    { en: "decadence", ko: "퇴폐" },
    { en: "decadent", ko: "퇴폐적인" },
    { en: "decapitate", ko: "참수하다" },
    { en: "decathlon", ko: "10종경기" },
    { en: "deceit", ko: "속임수" },
    { en: "deceitful", ko: "기만적인" },
    { en: "deceive", ko: "속이다" },
    { en: "decelerate", ko: "감속하다" },
    { en: "decency", ko: "예의" },
    { en: "decentralize", ko: "분산시키다" },
    { en: "deception", ko: "기만" },
    { en: "deceptive", ko: "기만적인" },
    { en: "decibel", ko: "데시벨" },
    { en: "deciduous", ko: "낙엽성의" },
    { en: "decimal", ko: "십진법의" },
    { en: "decimate", ko: "대량 학살하다" },
    { en: "decipher", ko: "해독하다" },
    { en: "decisive", ko: "결정적인" },
    { en: "declaration", ko: "선언" },
    { en: "declarative", ko: "선언적인" },
    { en: "declassify", ko: "기밀해제하다" },
    { en: "declination", ko: "하락" },
    { en: "decode", ko: "해독하다" },
    { en: "decompose", ko: "분해하다" },
    { en: "decomposition", ko: "분해" },
    { en: "decontaminate", ko: "오염을 제거하다" },
    { en: "decor", ko: "장식" },
    { en: "decorative", ko: "장식적인" },
    { en: "decorum", ko: "예의범절" },
    { en: "decoy", ko: "미끼" },

    // E-F (101-200)
    { en: "decree", ko: "법령" },
    { en: "decrepit", ko: "노쇠한" },
    { en: "decry", ko: "비난하다" },
    { en: "deduce", ko: "추론하다" },
    { en: "deduct", ko: "공제하다" },
    { en: "deductible", ko: "공제 가능한" },
    { en: "deduction", ko: "공제" },
    { en: "deductive", ko: "연역적인" },
    { en: "deface", ko: "훼손하다" },
    { en: "defamation", ko: "명예훼손" },
    { en: "defamatory", ko: "명예를 훼손하는" },
    { en: "defame", ko: "중상하다" },
    { en: "default", ko: "채무불이행" },
    { en: "defection", ko: "탈당" },
    { en: "defective", ko: "결함이 있는" },
    { en: "defector", ko: "탈북자" },
    { en: "defer", ko: "연기하다" },
    { en: "deference", ko: "경의" },
    { en: "deferential", ko: "공손한" },
    { en: "defiance", ko: "반항" },
    { en: "defiant", ko: "반항적인" },
    { en: "deficiency", ko: "결핍" },
    { en: "deficient", ko: "부족한" },
    { en: "defile", ko: "더럽히다" },
    { en: "definitive", ko: "결정적인" },
    { en: "deflate", ko: "바람을 빼다" },
    { en: "deflect", ko: "빗나가게 하다" },
    { en: "deflection", ko: "편향" },
    { en: "deforestation", ko: "삼림 벌채" },
    { en: "deform", ko: "변형시키다" },
    { en: "deformation", ko: "변형" },
    { en: "deformity", ko: "기형" },
    { en: "defraud", ko: "사취하다" },
    { en: "defray", ko: "지불하다" },
    { en: "deft", ko: "솜씨 좋은" },
    { en: "defunct", ko: "현존하지 않는" },
    { en: "defuse", ko: "제거하다" },
    { en: "degenerate", ko: "퇴화하다" },
    { en: "degeneration", ko: "퇴화" },
    { en: "degradation", ko: "저하" },
    { en: "degrade", ko: "저하시키다" },
    { en: "dehydrate", ko: "탈수시키다" },
    { en: "dehydration", ko: "탈수" },
    { en: "deify", ko: "신격화하다" },
    { en: "deign", ko: "~해 주시다" },
    { en: "deity", ko: "신" },
    { en: "dejected", ko: "낙담한" },
    { en: "dejection", ko: "낙담" },
    { en: "delectable", ko: "맛있는" },
    { en: "delegate", ko: "대표" },
    { en: "deliberation", ko: "숙고" },
    { en: "delicacy", ko: "섬세함" },
    { en: "delimit", ko: "한정하다" },
    { en: "delineate", ko: "기술하다" },
    { en: "delineation", ko: "묘사" },
    { en: "delinquency", ko: "비행" },
    { en: "delinquent", ko: "비행의" },
    { en: "delirious", ko: "정신착란의" },
    { en: "delirium", ko: "정신착란" },
    { en: "deliverance", ko: "구출" },
    { en: "delta", ko: "삼각주" },
    { en: "delude", ko: "속이다" },
    { en: "deluge", ko: "대홍수" },
    { en: "delusion", ko: "망상" },
    { en: "deluxe", ko: "고급의" },
    { en: "delve", ko: "파다" },
    { en: "demagogue", ko: "선동가" },
    { en: "demagoguery", ko: "선동" },
    { en: "demarcate", ko: "경계를 정하다" },
    { en: "demarcation", ko: "경계" },
    { en: "demean", ko: "품위를 떨어뜨리다" },
    { en: "demeaning", ko: "모욕적인" },
    { en: "demeanor", ko: "태도" },
    { en: "demented", ko: "미친" },
    { en: "dementia", ko: "치매" },
    { en: "demerit", ko: "결점" },
    { en: "demise", ko: "사망" },
    { en: "demobilize", ko: "동원해제하다" },
    { en: "democratize", ko: "민주화하다" },
    { en: "demolish", ko: "철거하다" },
    { en: "demolition", ko: "철거" },
    { en: "demon", ko: "악마" },
    { en: "demonic", ko: "악마의" },
    { en: "demonize", ko: "악마화하다" },
    { en: "demonstrable", ko: "증명할 수 있는" },
    { en: "demonstrative", ko: "표현하는" },
    { en: "demonstrator", ko: "시위자" },
    { en: "demoralize", ko: "사기를 꺾다" },
    { en: "demote", ko: "강등시키다" },
    { en: "demotion", ko: "강등" },
    { en: "demur", ko: "이의를 제기하다" },
    { en: "demure", ko: "얌전한" },
    { en: "demystify", ko: "신비성을 없애다" },
    { en: "den", ko: "굴" },
    { en: "denial", ko: "부인" },
    { en: "denigrate", ko: "폄하하다" },
    { en: "denigration", ko: "폄하" },
    { en: "denizen", ko: "거주자" },
    { en: "denomination", ko: "종파" },
    { en: "denote", ko: "나타내다" },

    // F-G (201-300)
    { en: "denouement", ko: "대단원" },
    { en: "denounce", ko: "비난하다" },
    { en: "density", ko: "밀도" },
    { en: "dent", ko: "움푹 들어간 곳" },
    { en: "dental", ko: "치과의" },
    { en: "dentist", ko: "치과의사" },
    { en: "denude", ko: "벌거벗기다" },
    { en: "denunciation", ko: "비난" },
    { en: "depict", ko: "묘사하다" },
    { en: "depiction", ko: "묘사" },
    { en: "deplete", ko: "고갈시키다" },
    { en: "depletion", ko: "고갈" },
    { en: "deplorable", ko: "개탄스러운" },
    { en: "deplore", ko: "개탄하다" },
    { en: "deployment", ko: "배치" },
    { en: "deport", ko: "추방하다" },
    { en: "deportation", ko: "추방" },
    { en: "deportee", ko: "추방자" },
    { en: "deportment", ko: "처신" },
    { en: "depose", ko: "폐위시키다" },
    { en: "deposition", ko: "증언" },
    { en: "depository", ko: "저장소" },
    { en: "depot", ko: "창고" },
    { en: "depravity", ko: "타락" },
    { en: "deprecate", ko: "반대하다" },
    { en: "depreciate", ko: "가치가 떨어지다" },
    { en: "depreciation", ko: "감가상각" },
    { en: "depress", ko: "우울하게 하다" },
    { en: "depressed", ko: "우울한" },
    { en: "depressant", ko: "진정제" },
    { en: "depressing", ko: "우울한" },
    { en: "deprivation", ko: "박탈" },
    { en: "deprived", ko: "빼앗긴" },
    { en: "deputy", ko: "대리인" },
    { en: "deranged", ko: "미친" },
    { en: "derangement", ko: "착란" },
    { en: "derelict", ko: "버려진" },
    { en: "dereliction", ko: "유기" },
    { en: "deride", ko: "비웃다" },
    { en: "derision", ko: "조롱" },
    { en: "derisive", ko: "조롱하는" },
    { en: "derisory", ko: "우스꽝스러운" },
    { en: "derivation", ko: "유래" },
    { en: "derivative", ko: "파생의" },
    { en: "dermatology", ko: "피부과학" },
    { en: "derogate", ko: "손상시키다" },
    { en: "derogatory", ko: "경멸적인" },
    { en: "descend", ko: "내려가다" },
    { en: "descendant", ko: "후손" },
    { en: "descent", ko: "하강" },
    { en: "desecrate", ko: "신성을 모독하다" },
    { en: "desecration", ko: "신성모독" },
    { en: "desegregate", ko: "차별을 폐지하다" },
    { en: "desegregation", ko: "차별 철폐" },
    { en: "deserter", ko: "탈영병" },
    { en: "desertion", ko: "탈영" },
    { en: "desiccate", ko: "건조시키다" },
    { en: "designation", ko: "지정" },
    { en: "designer", ko: "디자이너" },
    { en: "desirability", ko: "바람직함" },
    { en: "desirous", ko: "열망하는" },
    { en: "desist", ko: "그만두다" },
    { en: "desolate", ko: "황폐한" },
    { en: "desolation", ko: "황폐" },
    { en: "desperation", ko: "절망" },
    { en: "despicable", ko: "비열한" },
    { en: "despise", ko: "경멸하다" },
    { en: "despondent", ko: "낙담한" },
    { en: "despot", ko: "폭군" },
    { en: "despotic", ko: "폭군의" },
    { en: "despotism", ko: "전제정치" },
    { en: "dessert", ko: "디저트" },
    { en: "destabilize", ko: "불안정하게 하다" },
    { en: "destitute", ko: "극빈한" },
    { en: "destitution", ko: "극빈" },
    { en: "destructive", ko: "파괴적인" },
    { en: "desultory", ko: "산만한" },
    { en: "detach", ko: "분리하다" },
    { en: "detached", ko: "초연한" },
    { en: "detachment", ko: "분리" },
    { en: "detain", ko: "구금하다" },
    { en: "detainee", ko: "피구금자" },
    { en: "detect", ko: "감지하다" },
    { en: "detection", ko: "탐지" },
    { en: "detector", ko: "탐지기" },
    { en: "detention", ko: "구금" },
    { en: "deter", ko: "단념시키다" },
    { en: "detergent", ko: "세제" },
    { en: "deteriorate", ko: "악화되다" },
    { en: "deterioration", ko: "악화" },
    { en: "determinant", ko: "결정요인" },
    { en: "determinate", ko: "확정적인" },
    { en: "deterministic", ko: "결정론적인" },
    { en: "deterrence", ko: "억제" },
    { en: "deterrent", ko: "억제력" },
    { en: "detest", ko: "혐오하다" },
    { en: "detestable", ko: "혐오스러운" },
    { en: "dethrone", ko: "폐위시키다" },
    { en: "detonate", ko: "폭발시키다" },
    { en: "detonation", ko: "폭발" },
    { en: "detonator", ko: "기폭장치" },

    // G-H (301-400)
    { en: "detour", ko: "우회" },
    { en: "detox", ko: "해독" },
    { en: "detoxify", ko: "해독하다" },
    { en: "detract", ko: "손상시키다" },
    { en: "detractor", ko: "비방자" },
    { en: "detriment", ko: "손해" },
    { en: "detrimental", ko: "해로운" },
    { en: "detritus", ko: "잔해" },
    { en: "devalue", ko: "평가절하하다" },
    { en: "devaluation", ko: "평가절하" },
    { en: "devastate", ko: "황폐화시키다" },
    { en: "devastation", ko: "황폐" },
    { en: "deviant", ko: "일탈의" },
    { en: "deviate", ko: "벗어나다" },
    { en: "deviation", ko: "편차" },
    { en: "devious", ko: "교활한" },
    { en: "devoid", ko: "결여된" },
    { en: "devolution", ko: "권한이양" },
    { en: "devolve", ko: "위임하다" },
    { en: "devoted", ko: "헌신적인" },
    { en: "devotee", ko: "열성적인 지지자" },
    { en: "devotion", ko: "헌신" },
    { en: "devotional", ko: "신앙의" },
    { en: "devour", ko: "게걸스럽게 먹다" },
    { en: "devout", ko: "독실한" },
    { en: "dew", ko: "이슬" },
    { en: "dexterity", ko: "기민함" },
    { en: "dexterous", ko: "손재주 있는" },
    { en: "diabetes", ko: "당뇨병" },
    { en: "diabetic", ko: "당뇨병의" },
    { en: "diabolical", ko: "악마 같은" },
    { en: "diagnose", ko: "진단하다" },
    { en: "diagnostic", ko: "진단의" },
    { en: "diagonal", ko: "대각선의" },
    { en: "dialectic", ko: "변증법" },
    { en: "diameter", ko: "지름" },
    { en: "diametrically", ko: "정반대로" },
    { en: "diaper", ko: "기저귀" },
    { en: "diaphragm", ko: "횡경막" },
    { en: "diarrhea", ko: "설사" },
    { en: "diary", ko: "일기" },
    { en: "diaspora", ko: "디아스포라" },
    { en: "diatribe", ko: "통렬한 비난" },
    { en: "dichotomy", ko: "이분법" },
    { en: "diction", ko: "어법" },
    { en: "dictum", ko: "격언" },
    { en: "didactic", ko: "교훈적인" },
    { en: "diesel", ko: "디젤" },
    { en: "diffidence", ko: "자신감 부족" },
    { en: "diffident", ko: "자신없는" },
    { en: "diffuse", ko: "확산시키다" },
    { en: "diffusion", ko: "확산" },
    { en: "digestive", ko: "소화의" },
    { en: "digit", ko: "숫자" },
    { en: "digitize", ko: "디지털화하다" },
    { en: "dignify", ko: "품위있게 하다" },
    { en: "dignitary", ko: "고위인사" },
    { en: "digress", ko: "본론에서 벗어나다" },
    { en: "digression", ko: "탈선" },
    { en: "dilapidated", ko: "황폐한" },
    { en: "dilate", ko: "확대하다" },
    { en: "dilation", ko: "팽창" },
    { en: "dilatory", ko: "지연시키는" },
    { en: "dilemma", ko: "딜레마" },
    { en: "dilettante", ko: "아마추어" },
    { en: "diligence", ko: "근면" },
    { en: "dilute", ko: "희석하다" },
    { en: "dilution", ko: "희석" },
    { en: "dimensionality", ko: "차원" },
    { en: "diminutive", ko: "아주 작은" },
    { en: "din", ko: "소음" },
    { en: "dine", ko: "식사하다" },
    { en: "dingy", ko: "거무스름한" },
    { en: "dinosaur", ko: "공룡" },
    { en: "diocese", ko: "교구" },
    { en: "dioxide", ko: "이산화물" },
    { en: "dip", ko: "담그다" },
    { en: "diplomacy", ko: "외교" },
    { en: "diplomat", ko: "외교관" },
    { en: "dire", ko: "심각한" },
    { en: "directional", ko: "방향의" },
    { en: "directive", ko: "지시" },
    { en: "directorate", ko: "이사회" },
    { en: "dirge", ko: "장송곡" },
    { en: "disabled", ko: "장애가 있는" },
    { en: "disaffected", ko: "불만을 품은" },
    { en: "disambiguate", ko: "명확하게 하다" },
    { en: "disapproval", ko: "불찬성" },
    { en: "disapprove", ko: "비난하다" },
    { en: "disarm", ko: "무장해제시키다" },
    { en: "disarmament", ko: "군축" },
    { en: "disarming", ko: "마음을 여는" },
    { en: "disarray", ko: "무질서" },
    { en: "disassemble", ko: "분해하다" },
    { en: "disassociate", ko: "분리하다" },
    { en: "disavow", ko: "부인하다" },
    { en: "disavowal", ko: "부인" },
    { en: "disband", ko: "해산하다" },
    { en: "disbelief", ko: "불신" },
    { en: "disburse", ko: "지출하다" },
    { en: "disbursement", ko: "지출" },

    // H-I (401-500)
    { en: "discern", ko: "분별하다" },
    { en: "discernible", ko: "식별 가능한" },
    { en: "discerning", ko: "안목 있는" },
    { en: "discernment", ko: "통찰력" },
    { en: "disciple", ko: "제자" },
    { en: "disciplinarian", ko: "엄격한 사람" },
    { en: "disciplinary", ko: "징계의" },
    { en: "disclaim", ko: "부인하다" },
    { en: "disclaimer", ko: "부인" },
    { en: "disclose", ko: "밝히다" },
    { en: "disclosure", ko: "폭로" },
    { en: "disco", ko: "디스코" },
    { en: "discomfit", ko: "당황하게 하다" },
    { en: "discomfiture", ko: "당혹" },
    { en: "disconcert", ko: "당혹케 하다" },
    { en: "discontent", ko: "불만" },
    { en: "discontented", ko: "불만스러운" },
    { en: "discontinue", ko: "중단하다" },
    { en: "discontinuous", ko: "불연속적인" },
    { en: "discord", ko: "불화" },
    { en: "discordant", ko: "불협화음의" },
    { en: "discotheque", ko: "디스코텍" },
    { en: "discountenance", ko: "찬성하지 않다" },
    { en: "discredit", ko: "불신하게 하다" },
    { en: "discreet", ko: "신중한" },
    { en: "discrepancy", ko: "불일치" },
    { en: "discrete", ko: "별개의" },
    { en: "discretion", ko: "재량" },
    { en: "discretionary", ko: "재량의" },
    { en: "discriminate", ko: "차별하다" },
    { en: "discriminatory", ko: "차별적인" },
    { en: "discursive", ko: "산만한" },
    { en: "disdain", ko: "경멸" },
    { en: "disdainful", ko: "경멸하는" },
    { en: "disembark", ko: "하선하다" },
    { en: "disembodied", ko: "육체를 떠난" },
    { en: "disenchant", ko: "환멸을 느끼게 하다" },
    { en: "disenchantment", ko: "환멸" },
    { en: "disenfranchise", ko: "선거권을 박탈하다" },
    { en: "disengage", ko: "분리하다" },
    { en: "disengagement", ko: "분리" },
    { en: "disentangle", ko: "풀다" },
    { en: "disfavor", ko: "불신임" },
    { en: "disfigure", ko: "외모를 손상시키다" },
    { en: "disfigurement", ko: "외관 손상" },
    { en: "disfranchise", ko: "선거권을 박탈하다" },
    { en: "disgorge", ko: "토해내다" },
    { en: "disgraceful", ko: "수치스러운" },
    { en: "disgruntled", ko: "불만스러운" },
    { en: "disguise", ko: "변장" },
    { en: "disgust", ko: "혐오" },
    { en: "dishearten", ko: "낙담시키다" },
    { en: "disheveled", ko: "흐트러진" },
    { en: "dishonor", ko: "불명예" },
    { en: "dishonorable", ko: "불명예스러운" },
    { en: "disillusion", ko: "환멸" },
    { en: "disillusioned", ko: "환멸을 느낀" },
    { en: "disillusionment", ko: "환멸" },
    { en: "disincentive", ko: "억제책" },
    { en: "disinclination", ko: "싫어함" },
    { en: "disinclined", ko: "내키지 않는" },
    { en: "disinfect", ko: "소독하다" },
    { en: "disinfectant", ko: "소독제" },
    { en: "disinformation", ko: "허위정보" },
    { en: "disingenuous", ko: "진실되지 못한" },
    { en: "disinherit", ko: "상속권을 박탈하다" },
    { en: "disintegrate", ko: "분해되다" },
    { en: "disintegration", ko: "분해" },
    { en: "disinter", ko: "발굴하다" },
    { en: "disinterested", ko: "공정한" },
    { en: "disjunction", ko: "분리" },
    { en: "dislodge", ko: "밀어내다" },
    { en: "disloyal", ko: "불충한" },
    { en: "disloyalty", ko: "불충" },
    { en: "dismal", ko: "음울한" },
    { en: "dismantle", ko: "해체하다" },
    { en: "dismay", ko: "경악" },
    { en: "dismember", ko: "절단하다" },
    { en: "dismissal", ko: "해고" },
    { en: "dismissive", ko: "무시하는" },
    { en: "dismount", ko: "내리다" },
    { en: "disobedience", ko: "불복종" },
    { en: "disobedient", ko: "불복종하는" },
    { en: "disobey", ko: "불복종하다" },
    { en: "disorder", ko: "혼란" },
    { en: "disorderly", ko: "무질서한" },
    { en: "disorganize", ko: "혼란시키다" },
    { en: "disorient", ko: "방향감각을 잃게 하다" },
    { en: "disorientation", ko: "방향 상실" },
    { en: "disown", ko: "의절하다" },
    { en: "disparage", ko: "폄하하다" },
    { en: "disparagement", ko: "폄하" },
    { en: "disparate", ko: "이질적인" },
    { en: "disparity", ko: "격차" },
    { en: "dispassionate", ko: "냉정한" },
    { en: "dispatch", ko: "발송하다" },
    { en: "dispel", ko: "떨쳐버리다" },
    { en: "dispensable", ko: "없어도 되는" },
    { en: "dispensary", ko: "진료소" },
    { en: "dispensation", ko: "분배" },
    { en: "dispense", ko: "분배하다" },

    // I-J (501-600)
    { en: "dispenser", ko: "분배기" },
    { en: "dispersal", ko: "분산" },
    { en: "dispersion", ko: "분산" },
    { en: "dispirited", ko: "낙담한" },
    { en: "displacment", ko: "이동" },
    { en: "displeased", ko: "불쾌한" },
    { en: "displeasure", ko: "불쾌" },
    { en: "disposable", ko: "일회용의" },
    { en: "disproportionate", ko: "불균형한" },
    { en: "disprove", ko: "반증하다" },
    { en: "disputable", ko: "논쟁의 여지가 있는" },
    { en: "disputant", ko: "논쟁자" },
    { en: "disputation", ko: "논쟁" },
    { en: "disqualification", ko: "실격" },
    { en: "disqualify", ko: "실격시키다" },
    { en: "disquiet", ko: "불안" },
    { en: "disquieting", ko: "불안하게 하는" },
    { en: "disquisition", ko: "논문" },
    { en: "disregard", ko: "무시하다" },
    { en: "disrepair", ko: "황폐" },
    { en: "disreputable", ko: "평판이 나쁜" },
    { en: "disrepute", ko: "불명예" },
    { en: "disrespect", ko: "무례" },
    { en: "disrespectful", ko: "무례한" },
    { en: "disrobe", ko: "옷을 벗다" },
    { en: "disrupt", ko: "방해하다" },
    { en: "disruptive", ko: "방해하는" },
    { en: "dissatisfaction", ko: "불만" },
    { en: "dissatisfied", ko: "불만스러운" },
    { en: "dissect", ko: "해부하다" },
    { en: "dissection", ko: "해부" },
    { en: "dissemble", ko: "숨기다" },
    { en: "disseminate", ko: "보급하다" },
    { en: "dissemination", ko: "보급" },
    { en: "dissension", ko: "불화" },
    { en: "dissent", ko: "반대" },
    { en: "dissenter", ko: "반대자" },
    { en: "dissertation", ko: "논문" },
    { en: "disservice", ko: "해" },
    { en: "dissident", ko: "반체제 인사" },
    { en: "dissimilar", ko: "다른" },
    { en: "dissimilarity", ko: "상이함" },
    { en: "dissimulate", ko: "감추다" },
    { en: "dissipate", ko: "흩어지다" },
    { en: "dissipation", ko: "낭비" },
    { en: "dissociate", ko: "분리하다" },
    { en: "dissociation", ko: "분리" },
    { en: "dissolute", ko: "방탕한" },
    { en: "dissolution", ko: "해산" },
    { en: "dissonance", ko: "불협화음" },
    { en: "dissonant", ko: "불협화음의" },
    { en: "dissuade", ko: "단념시키다" },
    { en: "dissuasion", ko: "만류" },
    { en: "distant", ko: "멀리 있는" },
    { en: "distaste", ko: "혐오" },
    { en: "distasteful", ko: "불쾌한" },
    { en: "distend", ko: "팽창시키다" },
    { en: "distension", ko: "팽창" },
    { en: "distill", ko: "증류하다" },
    { en: "distillation", ko: "증류" },
    { en: "distillery", ko: "증류소" },
    { en: "distinctive", ko: "독특한" },
    { en: "distinctly", ko: "뚜렷하게" },
    { en: "distortion", ko: "왜곡" },
    { en: "distraction", ko: "주의산만" },
    { en: "distraught", ko: "제정신이 아닌" },
    { en: "distressing", ko: "괴로운" },
    { en: "distribution", ko: "분배" },
    { en: "district", ko: "지구" },
    { en: "distrust", ko: "불신" },
    { en: "distrustful", ko: "의심하는" },
    { en: "disturbing", ko: "불안하게 하는" },
    { en: "disunity", ko: "분열" },
    { en: "disuse", ko: "폐기" },
    { en: "diverge", ko: "갈라지다" },
    { en: "divergence", ko: "분기" },
    { en: "divergent", ko: "분기하는" },
    { en: "diversification", ko: "다양화" },
    { en: "diversify", ko: "다양화하다" },
    { en: "diversion", ko: "우회" },
    { en: "divest", ko: "빼앗다" },
    { en: "divestiture", ko: "매각" },
    { en: "dividend", ko: "배당금" },
    { en: "divination", ko: "점" },
    { en: "divinity", ko: "신성" },
    { en: "divisible", ko: "나눌 수 있는" },
    { en: "divisive", ko: "분열시키는" },
    { en: "divorcee", ko: "이혼한 사람" },
    { en: "divulge", ko: "누설하다" },
    { en: "dizziness", ko: "어지러움" },
    { en: "dizzy", ko: "어지러운" },
    { en: "docile", ko: "유순한" },
    { en: "docility", ko: "유순함" },
    { en: "dock", ko: "부두" },
    { en: "docket", ko: "소송사건 목록" },
    { en: "doctrine", ko: "교리" },
    { en: "doctrinal", ko: "교리의" },
    { en: "documentary", ko: "다큐멘터리" },
    { en: "documentation", ko: "문서화" },
    { en: "dodder", ko: "비틀거리다" },
    { en: "dodge", ko: "피하다" },

    // J-K (601-700)
    { en: "doff", ko: "벗다" },
    { en: "dogged", ko: "끈질긴" },
    { en: "dogma", ko: "교리" },
    { en: "dogmatic", ko: "독단적인" },
    { en: "dogmatism", ko: "독단주의" },
    { en: "doldrums", ko: "침체" },
    { en: "dole", ko: "실업수당" },
    { en: "doleful", ko: "슬픈" },
    { en: "doll", ko: "인형" },
    { en: "dolorous", ko: "슬픔에 찬" },
    { en: "dolphin", ko: "돌고래" },
    { en: "domain", ko: "영역" },
    { en: "dome", ko: "돔" },
    { en: "domesticate", ko: "길들이다" },
    { en: "domestication", ko: "가축화" },
    { en: "domesticity", ko: "가정생활" },
    { en: "domicile", ko: "거주지" },
    { en: "dominance", ko: "지배" },
    { en: "domineering", ko: "횡포한" },
    { en: "dominion", ko: "지배권" },
    { en: "don", ko: "입다" },
    { en: "donation", ko: "기부" },
    { en: "donor", ko: "기증자" },
    { en: "doomsday", ko: "최후의 심판일" },
    { en: "doorstep", ko: "문지방" },
    { en: "doorway", ko: "출입구" },
    { en: "dope", ko: "마약" },
    { en: "dormant", ko: "휴면 상태의" },
    { en: "dormitory", ko: "기숙사" },
    { en: "dosage", ko: "투여량" },
    { en: "dossier", ko: "서류철" },
    { en: "dote", ko: "맹목적으로 사랑하다" },
    { en: "doting", ko: "맹목적으로 사랑하는" },
    { en: "doubly", ko: "이중으로" },
    { en: "doubtless", ko: "의심할 여지없이" },
    { en: "dour", ko: "무뚝뚝한" },
    { en: "douse", ko: "끄다" },
    { en: "dove", ko: "비둘기" },
    { en: "dowdy", ko: "촌스러운" },
    { en: "downtrodden", ko: "짓밟힌" },
    { en: "downturn", ko: "하락" },
    { en: "dowry", ko: "지참금" },
    { en: "doze", ko: "졸다" },
    { en: "drab", ko: "단조로운" },
    { en: "draconian", ko: "엄격한" },
    { en: "draft", ko: "초안" },
    { en: "draftsman", ko: "제도사" },
    { en: "dragnet", ko: "수사망" },
    { en: "drainage", ko: "배수" },
    { en: "dramatize", ko: "극화하다" },
    { en: "drape", ko: "휘장" },
    { en: "drapery", ko: "커튼" },
    { en: "drawback", ko: "결점" },
    { en: "dreadful", ko: "무시무시한" },
    { en: "dreary", ko: "우울한" },
    { en: "drench", ko: "흠뻑 적시다" },
    { en: "dressing", ko: "드레싱" },
    { en: "dribble", ko: "드리블하다" },
    { en: "drip", ko: "똑똑 떨어지다" },
    { en: "drivel", ko: "헛소리" },
    { en: "droll", ko: "우스꽝스러운" },
    { en: "drone", ko: "드론" },
    { en: "drool", ko: "침을 흘리다" },
    { en: "droop", ko: "처지다" },
    { en: "dropout", ko: "중퇴자" },
    { en: "dross", ko: "쓸모없는 것" },
    { en: "drought", ko: "가뭄" },
    { en: "drove", ko: "떼" },
    { en: "drowsy", ko: "졸린" },
    { en: "drudge", ko: "고되게 일하다" },
    { en: "drudgery", ko: "고된 일" },
    { en: "drugstore", ko: "약국" },
    { en: "drummer", ko: "드러머" },
    { en: "drumstick", ko: "북채" },
    { en: "drunkard", ko: "술주정뱅이" },
    { en: "drunken", ko: "술 취한" },
    { en: "dryness", ko: "건조함" },
    { en: "dubious", ko: "의심스러운" },
    { en: "duct", ko: "관" },
    { en: "ductile", ko: "연성의" },
    { en: "dud", ko: "불발탄" },
    { en: "dude", ko: "녀석" },
    { en: "duel", ko: "결투" },
    { en: "duet", ko: "이중창" },
    { en: "duke", ko: "공작" },
    { en: "duly", ko: "정당하게" },
    { en: "dumbfound", ko: "어리둥절하게 하다" },
    { en: "dummy", ko: "모형" },
    { en: "dumpling", ko: "만두" },
    { en: "dunce", ko: "바보" },
    { en: "dune", ko: "모래 언덕" },
    { en: "dungeon", ko: "지하 감옥" },
    { en: "dupe", ko: "속이다" },
    { en: "duplicate", ko: "복사하다" },
    { en: "duplication", ko: "중복" },
    { en: "duplicity", ko: "이중성" },
    { en: "durability", ko: "내구성" },
    { en: "duress", ko: "강압" },
    { en: "dutiful", ko: "충실한" },
    { en: "dweller", ko: "거주자" },
    { en: "dwindle", ko: "줄어들다" },

    // K-L (701-800)
    { en: "dye", ko: "염료" },
    { en: "dynamics", ko: "역학" },
    { en: "dynamism", ko: "역동성" },
    { en: "dynamite", ko: "다이너마이트" },
    { en: "dynamo", ko: "발전기" },
    { en: "dynastic", ko: "왕조의" },
    { en: "dynasty", ko: "왕조" },
    { en: "dysfunction", ko: "기능 장애" },
    { en: "dysfunctional", ko: "기능 장애의" },
    { en: "dyslexia", ko: "난독증" },
    { en: "dyslexic", ko: "난독증의" },
    { en: "dystopia", ko: "디스토피아" },
    { en: "dystopian", ko: "디스토피아적인" },
    { en: "eager", ko: "열망하는" },
    { en: "eagerness", ko: "열망" },
    { en: "eardrum", ko: "고막" },
    { en: "earl", ko: "백작" },
    { en: "earnest", ko: "진지한" },
    { en: "earnestness", ko: "진지함" },
    { en: "earphone", ko: "이어폰" },
    { en: "earring", ko: "귀걸이" },
    { en: "earthen", ko: "흙의" },
    { en: "earthenware", ko: "토기" },
    { en: "earthly", ko: "세속적인" },
    { en: "earthworm", ko: "지렁이" },
    { en: "earthy", ko: "소박한" },
    { en: "easel", ko: "이젤" },
    { en: "eavesdrop", ko: "엿듣다" },
    { en: "ebb", ko: "썰물" },
    { en: "ebony", ko: "흑단" },
    { en: "ebullient", ko: "열광적인" },
    { en: "eccentric", ko: "별난" },
    { en: "eccentricity", ko: "별남" },
    { en: "ecclesiastical", ko: "교회의" },
    { en: "echelon", ko: "계층" },
    { en: "eclectic", ko: "절충적인" },
    { en: "eclecticism", ko: "절충주의" },
    { en: "eclipse", ko: "일식" },
    { en: "ecologist", ko: "생태학자" },
    { en: "ecology", ko: "생태학" },
    { en: "economic", ko: "경제의" },
    { en: "economical", ko: "경제적인" },
    { en: "economize", ko: "절약하다" },
    { en: "ecosystem", ko: "생태계" },
    { en: "ecstasy", ko: "황홀경" },
    { en: "ecstatic", ko: "황홀한" },
    { en: "ecumenical", ko: "세계적인" },
    { en: "eddy", ko: "소용돌이" },
    { en: "edema", ko: "부종" },
    { en: "edict", ko: "칙령" },
    { en: "edification", ko: "교화" },
    { en: "edifice", ko: "건물" },
    { en: "edify", ko: "교화하다" },
    { en: "edit", ko: "편집하다" },
    { en: "edition", ko: "판" },
    { en: "editorial", ko: "사설" },
    { en: "educate", ko: "교육하다" },
    { en: "eerie", ko: "으스스한" },
    { en: "efface", ko: "지우다" },
    { en: "effectuate", ko: "실현하다" },
    { en: "effeminate", ko: "여성스러운" },
    { en: "effervesce", ko: "거품이 이다" },
    { en: "effervescent", ko: "거품이 이는" },
    { en: "efficacious", ko: "효과적인" },
    { en: "efficacy", ko: "효능" },
    { en: "efficiency", ko: "효율성" },
    { en: "effigy", ko: "초상" },
    { en: "effluent", ko: "폐수" },
    { en: "efflux", ko: "유출" },
    { en: "effortless", ko: "수월한" },
    { en: "effrontery", ko: "뻔뻔스러움" },
    { en: "effulgent", ko: "찬란한" },
    { en: "effusion", ko: "유출" },
    { en: "effusive", ko: "감정적인" },
    { en: "egalitarian", ko: "평등주의의" },
    { en: "egalitarianism", ko: "평등주의" },
    { en: "egghead", ko: "인텔리" },
    { en: "egocentrism", ko: "자기중심주의" },
    { en: "egoism", ko: "이기주의" },
    { en: "egoist", ko: "이기주의자" },
    { en: "egoistic", ko: "이기적인" },
    { en: "egotism", ko: "자기 과시" },
    { en: "egotist", ko: "이기주의자" },
    { en: "egotistical", ko: "자기중심적인" },
    { en: "egregious", ko: "지독한" },
    { en: "ejaculate", ko: "외치다" },
    { en: "eject", ko: "내쫓다" },
    { en: "ejection", ko: "배출" },
    { en: "elaborate", ko: "정교한" },
    { en: "elaboration", ko: "정교화" },
    { en: "elapse", ko: "경과하다" },
    { en: "elastic", ko: "탄력적인" },
    { en: "elasticity", ko: "탄력성" },
    { en: "elate", ko: "기쁘게 하다" },
    { en: "elation", ko: "기쁨" },
    { en: "elbow", ko: "팔꿈치" },
    { en: "elder", ko: "연장자" },
    { en: "elderly", ko: "나이 든" },
    { en: "elective", ko: "선택의" },
    { en: "electoral", ko: "선거의" },
    { en: "electorate", ko: "선거인단" },

    // L-M (801-900)
    { en: "electrify", ko: "전기를 통하게 하다" },
    { en: "electrocardiogram", ko: "심전도" },
    { en: "electrode", ko: "전극" },
    { en: "electrolyte", ko: "전해질" },
    { en: "electromagnetic", ko: "전자기의" },
    { en: "electronically", ko: "전자적으로" },
    { en: "electronics", ko: "전자공학" },
    { en: "elegance", ko: "우아함" },
    { en: "elegy", ko: "비가" },
    { en: "elemental", ko: "기본적인" },
    { en: "elementary", ko: "기본적인" },
    { en: "elevate", ko: "높이다" },
    { en: "elevation", ko: "고도" },
    { en: "elicit", ko: "이끌어내다" },
    { en: "eligibility", ko: "자격" },
    { en: "eliminate", ko: "제거하다" },
    { en: "elimination", ko: "제거" },
    { en: "elite", ko: "엘리트" },
    { en: "elitism", ko: "엘리트주의" },
    { en: "elitist", ko: "엘리트주의자" },
    { en: "elixir", ko: "영약" },
    { en: "elk", ko: "엘크" },
    { en: "ellipse", ko: "타원" },
    { en: "ellipsis", ko: "생략" },
    { en: "elliptical", ko: "타원형의" },
    { en: "elm", ko: "느릅나무" },
    { en: "elocution", ko: "웅변술" },
    { en: "elongate", ko: "늘이다" },
    { en: "elongation", ko: "신장" },
    { en: "elope", ko: "야반도주하다" },
    { en: "elopement", ko: "야반도주" },
    { en: "eloquence", ko: "웅변" },
    { en: "eloquent", ko: "웅변의" },
    { en: "elucidate", ko: "밝히다" },
    { en: "elucidation", ko: "해명" },
    { en: "elude", ko: "피하다" },
    { en: "elusive", ko: "포착하기 어려운" },
    { en: "emaciate", ko: "수척하게 하다" },
    { en: "emaciated", ko: "수척한" },
    { en: "emancipate", ko: "해방하다" },
    { en: "emancipation", ko: "해방" },
    { en: "embalm", ko: "방부 처리하다" },
    { en: "embargo", ko: "금수조치" },
    { en: "embark", ko: "승선하다" },
    { en: "embarkation", ko: "승선" },
    { en: "embarrass", ko: "당혹스럽게 하다" },
    { en: "embarrassing", ko: "당혹스러운" },
    { en: "embarrassment", ko: "당혹" },
    { en: "embassy", ko: "대사관" },
    { en: "embattle", ko: "전투 태세를 취하다" },
    { en: "embattled", ko: "곤경에 처한" },
    { en: "embedded", ko: "내장된" },
    { en: "embellish", ko: "장식하다" },
    { en: "embellishment", ko: "장식" },
    { en: "ember", ko: "잔불" },
    { en: "embezzle", ko: "횡령하다" },
    { en: "embezzlement", ko: "횡령" },
    { en: "embitter", ko: "괴롭히다" },
    { en: "embittered", ko: "분개한" },
    { en: "emblazon", ko: "장식하다" },
    { en: "emblem", ko: "상징" },
    { en: "emblematic", ko: "상징적인" },
    { en: "embodiment", ko: "구현" },
    { en: "embolden", ko: "용기를 북돋우다" },
    { en: "embolism", ko: "색전증" },
    { en: "emboss", ko: "양각하다" },
    { en: "embracement", ko: "포옹" },
    { en: "embroider", ko: "수놓다" },
    { en: "embroidery", ko: "자수" },
    { en: "embroil", ko: "말려들게 하다" },
    { en: "embryonic", ko: "초기의" },
    { en: "emcee", ko: "사회자" },
    { en: "emerald", ko: "에메랄드" },
    { en: "emerge", ko: "나타나다" },
    { en: "emergence", ko: "출현" },
    { en: "emergent", ko: "신흥의" },
    { en: "emigrant", ko: "이민자" },
    { en: "emigrate", ko: "이민가다" },
    { en: "emigration", ko: "이민" },
    { en: "eminence", ko: "명성" },
    { en: "eminent", ko: "저명한" },
    { en: "eminently", ko: "매우" },
    { en: "emir", ko: "에미르" },
    { en: "emirate", ko: "토후국" },
    { en: "emissary", ko: "밀사" },
    { en: "emission", ko: "배출" },
    { en: "emit", ko: "방출하다" },
    { en: "emollient", ko: "완화제" },
    { en: "emolument", ko: "보수" },
    { en: "emote", ko: "감정을 표현하다" },
    { en: "emoticon", ko: "이모티콘" },
    { en: "emotional", ko: "감정적인" },
    { en: "emotionally", ko: "감정적으로" },
    { en: "emotive", ko: "감정적인" },
    { en: "empathetic", ko: "공감하는" },
    { en: "empathize", ko: "공감하다" },
    { en: "empathy", ko: "공감" },
    { en: "emperor", ko: "황제" },
    { en: "emphasize", ko: "강조하다" },
    { en: "emphatic", ko: "단호한" },
    { en: "emphatically", ko: "단호하게" },

    // M-N (901-1000)
    { en: "empiricism", ko: "경험주의" },
    { en: "employ", ko: "고용하다" },
    { en: "employable", ko: "고용 가능한" },
    { en: "employment", ko: "고용" },
    { en: "emporium", ko: "대상점" },
    { en: "empowerment", ko: "권한 부여" },
    { en: "empress", ko: "여제" },
    { en: "emptiness", ko: "공허함" },
    { en: "emulate", ko: "모방하다" },
    { en: "emulation", ko: "모방" },
    { en: "enable", ko: "가능하게 하다" },
    { en: "enact", ko: "법률을 제정하다" },
    { en: "enactment", ko: "제정" },
    { en: "enamel", ko: "에나멜" },
    { en: "enamor", ko: "반하게 하다" },
    { en: "encampment", ko: "야영" },
    { en: "encapsulate", ko: "요약하다" },
    { en: "encase", ko: "넣다" },
    { en: "enchant", ko: "매혹하다" },
    { en: "enchanting", ko: "매혹적인" },
    { en: "enchantment", ko: "매혹" },
    { en: "encircle", ko: "에워싸다" },
    { en: "enclave", ko: "고립지역" },
    { en: "enclose", ko: "동봉하다" },
    { en: "enclosure", ko: "울타리" },
    { en: "encode", ko: "부호화하다" },
    { en: "encompass", ko: "포함하다" },
    { en: "encore", ko: "앙코르" },
    { en: "encounter", ko: "만남" },
    { en: "encourage", ko: "격려하다" },
    { en: "encouraging", ko: "격려하는" },
    { en: "encroach", ko: "침해하다" },
    { en: "encroachment", ko: "침해" },
    { en: "encrypt", ko: "암호화하다" },
    { en: "encryption", ko: "암호화" },
    { en: "encumber", ko: "방해하다" },
    { en: "encumbrance", ko: "방해물" },
    { en: "encyclopedia", ko: "백과사전" },
    { en: "encyclopedic", ko: "백과사전적인" },
    { en: "endanger", ko: "위험에 빠뜨리다" },
    { en: "endangerment", ko: "위험에 빠뜨림" },
    { en: "endear", ko: "사랑받게 하다" },
    { en: "endearing", ko: "사랑스러운" },
    { en: "endearment", ko: "애정표현" },
    { en: "endemic", ko: "풍토병의" },
    { en: "endocrine", ko: "내분비의" },
    { en: "endorse", ko: "지지하다" },
    { en: "endorsement", ko: "지지" },
    { en: "endow", ko: "부여하다" },
    { en: "endowment", ko: "기부금" },
    { en: "endpoint", ko: "종점" },
    { en: "endurable", ko: "견딜 수 있는" },
    { en: "endure", ko: "견디다" },
    { en: "enduring", ko: "지속적인" },
    { en: "energize", ko: "활력을 주다" },
    { en: "enervate", ko: "약화시키다" },
    { en: "enfeeble", ko: "약화시키다" },
    { en: "enforce", ko: "시행하다" },
    { en: "enforceable", ko: "시행 가능한" },
    { en: "enforcement", ko: "시행" },
    { en: "enfranchise", ko: "선거권을 주다" },
    { en: "enfranchisement", ko: "선거권 부여" },
    { en: "engage", ko: "참여시키다" },
    { en: "engaged", ko: "약혼한" },
    { en: "engaging", ko: "매력적인" },
    { en: "engender", ko: "야기하다" },
    { en: "engine", ko: "엔진" },
    { en: "engineer", ko: "기술자" },
    { en: "engineering", ko: "공학" },
    { en: "engrave", ko: "새기다" },
    { en: "engraving", ko: "조각" },
    { en: "engross", ko: "몰두시키다" },
    { en: "engrossing", ko: "몰두하게 하는" },
    { en: "engulf", ko: "삼키다" },
    { en: "enhance", ko: "향상시키다" },
    { en: "enhancement", ko: "향상" },
    { en: "enigma", ko: "수수께끼" },
    { en: "enigmatic", ko: "수수께끼 같은" },
    { en: "enjoin", ko: "명하다" },
    { en: "enjoyable", ko: "즐거운" },
    { en: "enjoyment", ko: "즐거움" },
    { en: "enlarge", ko: "확대하다" },
    { en: "enlargement", ko: "확대" },
    { en: "enlighten", ko: "계몽하다" },
    { en: "enlightened", ko: "계몽된" },
    { en: "enlightening", ko: "계몽적인" },
    { en: "enlist", ko: "입대하다" },
    { en: "enlistment", ko: "입대" },
    { en: "enliven", ko: "활기를 띠게 하다" },
    { en: "enmity", ko: "적의" },
    { en: "ennui", ko: "권태" },
    { en: "enormity", ko: "극악무도함" },
    { en: "enormous", ko: "거대한" },
    { en: "enormously", ko: "엄청나게" },
    { en: "enquire", ko: "문의하다" },
    { en: "enquiry", ko: "문의" },
    { en: "enrage", ko: "격분시키다" },
    { en: "enraged", ko: "격분한" },
    { en: "enrapture", ko: "황홀하게 하다" },
    { en: "enrich", ko: "풍요롭게 하다" }
];
